[general]
OPENAI_API_KEY = "your_openai_api_key_heresk-proj-7C-p3w37TP7EA8-7tRs6MpMs-drU19JpgF4Qcarj01UXMWycHJJUyEGNubQTMMilxEMo9yjXC9T3BlbkFJjQiLgH1pasEj0Jw9i1e2CDvnuSebQWqtOnnEVdqkjO7wKrvtm5e_RTvOR2vD2zv4I4V4ok3EkA"